apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: severed-head-sunday-web
  namespace: severed-head-sunday
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:058264155697:certificate/ce2209c8-6d9f-4204-be52-01d16d8a5234
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /health 
spec:
  ingressClassName: alb
  rules:
    - host: severedheadsunday.band
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: severed-head-sunday-web
                port:
                  number: 80
